# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from robotgo.static.proto_files import (
    test_pb2 as robotgo_dot_static_dot_proto__files_dot_test__pb2,
)


class PathFinderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetField = channel.unary_unary(
            "/PathFinder/SetField",
            request_serializer=robotgo_dot_static_dot_proto__files_dot_test__pb2.Field.SerializeToString,
            response_deserializer=robotgo_dot_static_dot_proto__files_dot_test__pb2.Empty.FromString,
        )
        self.Moving = channel.stream_stream(
            "/PathFinder/Moving",
            request_serializer=robotgo_dot_static_dot_proto__files_dot_test__pb2.MoveRequest.SerializeToString,
            response_deserializer=robotgo_dot_static_dot_proto__files_dot_test__pb2.MoveResponse.FromString,
        )


class PathFinderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetField(self, request, context):
        """инициализация начального состояния"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Moving(self, request_iterator, context):
        """процесс движения"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PathFinderServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SetField": grpc.unary_unary_rpc_method_handler(
            servicer.SetField,
            request_deserializer=robotgo_dot_static_dot_proto__files_dot_test__pb2.Field.FromString,
            response_serializer=robotgo_dot_static_dot_proto__files_dot_test__pb2.Empty.SerializeToString,
        ),
        "Moving": grpc.stream_stream_rpc_method_handler(
            servicer.Moving,
            request_deserializer=robotgo_dot_static_dot_proto__files_dot_test__pb2.MoveRequest.FromString,
            response_serializer=robotgo_dot_static_dot_proto__files_dot_test__pb2.MoveResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "PathFinder", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class PathFinder(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetField(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/PathFinder/SetField",
            robotgo_dot_static_dot_proto__files_dot_test__pb2.Field.SerializeToString,
            robotgo_dot_static_dot_proto__files_dot_test__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Moving(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/PathFinder/Moving",
            robotgo_dot_static_dot_proto__files_dot_test__pb2.MoveRequest.SerializeToString,
            robotgo_dot_static_dot_proto__files_dot_test__pb2.MoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
